[package]
name = "pcm-reader"
version = "0.1.0"
authors = ["gmazzeo <mazzeo.gio@gmail.com>"]

[dependencies]
x86 ={git='https://github.com/dzobbe/rust-x86.git'}
perfcnt={git='https://github.com/dzobbe/rust-perfcnt.git'}
time = "*"
raw-cpuid = "2.0.1"
docopt = "0.6"
rustc-serialize = "0.3" 
